version: '3'
services:
  mongodb:
    container_name: mongodb_container
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - workers

  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command: sh /mongo-seed/import.sh
    networks:
      - workers

  redis:
    container_name: redis_container
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - workers

  worker_app:
    container_name: worker_app_container
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    networks:
      - workers
    command: npm start

networks:
  workers:
    driver: bridge
